export interface WordEntry {
  id?: number; // Optional: will be auto-generated by the database
  word: string;
  part_of_speech: string;
  definition: string; // Storing bullet points as a single string, can be parsed on frontend
  difficulty_level: string; // e.g., A1, A2, B1
  example_sentence: string;
  option_a: string; // Correct answer
  option_b: string;
  option_c: string;
  option_d: string;
  created_at?: Date; // Optional: will be auto-generated
  updated_at?: Date; // Optional: will be auto-generated
  update_note?: string | null;
  placeholder_1?: any; // Placeholder for future enhancement
  placeholder_2?: any; // Placeholder for future enhancement
}